version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ~/scoutbot-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scoutbot
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - scoutbot-network

  scoutbot:
    build: .
    restart: always
    env_file: 
      - .env
    depends_on:
      - mysql
    networks:
      - scoutbot-network
    ports:
      - "8000:80"

networks:
  scoutbot-network:
